### ISSUE TITLE
Централизованное управление загрузкой данных

### ISSUE THREAD

**Issue by avtopro** [thekolesnikov/vin-decoder-react#1]
Метод fetchVinInfo используется двумя компонентами: Input и LastRequests таким образом, что возможны параллельные запросы, вызванные как одним из компонентов, так и двумя сразу. Например, можно несколько раз нажать на код (или разные коды) из списка "Last Requests" и выполнится несколько запросов, а можно, если постараться, отправить один код через форму поиска и сразу же нажать на другой код из истории — какой результат расшифровки в итоге отобразится, будет зависеть от времени выполнения каждого из запросов (совершенно не гарантируется, что они будут выполнены именно в порядке вызова). Таким образом может возникнуть состояние гонки запросов, с довольно непредсказуемым результатом.

https://github.com/thekolesnikov/vin-decoder-react/blob/fb460f1acc9a4a72d07fa6096e527844ccb3906a/src/components/LastRequests/LastRequests.jsx#LL19C33-L28C35

Правильнее было бы вынести код, отвечающий за вызов fetchVinInfo, на верхний уровень, например HomePage и там реализовать:
- Блокировку повторной отправки одного и того же VIN, пока предыдущий запрос не завершён.
- Возможно, отмену предыдущего запроса, если поступает новый запрос по другому VIN.

То есть, каким-то образом гарантировать что в интерфейсе будет отображена информация по VIN, который был запрошен последним, или хотя бы просто убрать возможность делать параллельные запросы. К тому же, код, в котором fetchVinInfo вызывается только одним определённым модулем, становится чуть прозрачнее.

**Comment by thekolesnikov** [comment]
@avtopro Спасибо за развёрнутый комментарий

### Fixed:
- Вынес логику отправки запросов в HomePage, что позволило избавиться от прокидывания лишних пропсов и дублирования кода в дочерних компонентах. Также, теперь новые запросы на сервер будут отправляться только если isLoading равен false.
- Изменил UI при ожидании ответа от сервера. Теперь инпут, кнопка отправки формы и список последних вин кодов будут неактивны, пока не завершится запрос и isLoading не станет равен false.
